### ISSUE TITLE
Select typography

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#10]
Website
- [x] Primary nav
- [x] Tabs
- [x] Footer
- [x] Body copy
- [x] Listing title
- [x] Line title
- [x] Quick look block
- [x] Details
- [x] Contact info
- [x] Event mixings basic
- [x] Event mixing premium
- [x] Business unit mixing basic
- [x] Business unit mixing premium
- [x] Listing feature
- [x] Link style
- [x] Button style

Printed map
- [x] Markers
- [x] Legend
- [x] Lables
- [x] Calls to action

Finalised
- [x] Changes finalised in CSS
- [x] Changes finalised in In Design
- [ ] Lou approved

**Comment by angievanhegan** [comment]
unblocker is #20

**Comment by lolmos** [comment]
ready for review: https://the.holboxeno.com/en/food-drink-in-holbox/bar-1-premium-plus

**Comment by angievanhegan** [comment]
@lolmos some feedback on body copy. This is totally fine, but for what it's worth, Tim and I would prefer something plainer and more standard. Just to make it as easy as possible on the eye. 

Let me know when you're free to go through this with me so I know which is which.  Unless it's easier to change the text on the page to match the titles here on the issue? i.e. make the listing title on the page say 'listing title'. Up to you.

**Comment by angievanhegan** [comment]
Just printed map styles to check and sign off.
