### ISSUE TITLE
Put the basic BU content items at the top of the form

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#101]
### Basic
- [ ] BU name
- [ ] meta title English
- [ ] Meta title Spanish
- [ ] Business type
- [ ] Business sub type
- [ ] What to expect
- [ ] Cost low/high*
- [ ] opening time (english)*
- [ ] opening time Spanish*
- [ ] Telephone*
- [ ] geo location
- [ ] Address

### Basic plus
- [ ] Gallery image English (only one!)
- [ ] Gallery image Spanish (sólo una!)

**Comment by lolmos** [comment]
done
