### ISSUE TITLE
Show on listing and content pages what type of content it is (to help with showing/selling the site)

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#106]
- [ ] Basic BU
- [ ] Basic plus BU
- [ ] Premium BU
- [ ] Premium plus BU
- [ ] Basic event
- [ ] Premium event

**Comment by lolmos** [comment]
I think the better solution is to make one of each and give it that name as a clear example. people are gonna keep asking if it's going to be there later

**Comment by lolmos** [comment]
@angievanhegan what thinkest thou?

**Comment by angievanhegan** [comment]
@lolmos With latin/greek text?
