### ISSUE TITLE
Writing better spanish

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#117]
- [ ] All narrative on events and BU in Spanish and English content is of good quality

If you really want to use the fact that there will be great writing and great spanish on the site, perhaps you should put this on the MVP site (i.e. the premium and premium plus examples) so that people see this when they're making their first impression of the site.

**Comment by lolmos** [comment]
Have written all the content. no more google translate

**Comment by lolmos** [comment]
@angievanhegan this is resolved
