### ISSUE TITLE
Get usability feedback from people

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#121]
- [ ] Create a list of tasks/tests
# 
- [ ] Kevin
- [ ] Nancy
- [ ] Kyle
- [ ] Alyson
- [ ] Calum
- [ ] Maz
- [ ] Teeny
- [ ] Malc
- [ ] Leonard
- [ ] Jab
- [ ] Rav
- [ ] Stevie
- [ ] Ang May

**Comment by lolmos** [comment]
https://www.hotjar.com
