### ISSUE TITLE
Create flat style guide

### ISSUE THREAD

**Issue by lolmos** [lolmos/statictestting#13]
Prep single page for style guide

Done Criteria:
- [x] Primary nav
- [x] Tabs
- [x] Footer
- [x] Body copy
- [x] Blockquote
- [x] Listing title
- [x] Line title
- [x] Quick look block
- [x] Details
- [x] Contact info
- [x] Event mixings plain
- [x] Event mixing premium
- [x] Business unit mixing basic
- [x] Business unit mixing premium
- [x] Business unit mixing premium+
- [x] Listing feature
- [x] Link style
- [x] Button style

**Comment by angievanhegan** [comment]
@lolmos You can sign this off though? It's just a tick list that you have one of everything. Lou's going to sign off the actual design of them. I'd say move this to done.
