### ISSUE TITLE
write premium content

### ISSUE THREAD

**Issue by lolmos** [lolmos/statictestting#18]
#### La Chilanguita
- [x]  [ ]  general description
- [x] [ ] recomendation
- [x] [ ] price low and high

#### Milpa
- [x] [ ] general description
- [x] [ ] recomendation
- [x] [ ] price low and high

#### Bar Arena
- [x] [ ] general description
- [x] [ ] recomendation
- [x] [ ] price low and high

#### Cariocas
- [x] [ ]  general description
- [x] [ ]  recomendation
- [x] [ ] price low and high

**Comment by Loubielou** [comment]
What do you mean by price high and low?

**Comment by Loubielou** [comment]
I've completed these..do you want to check them before I put them in the finished section of the Waffle? There are a few details we need to add (telephone numbers etc.), but the text is written  in English. They'll need translating :)

**Comment by Loubielou** [comment]
The texts are in Dropbox by the way. The document is called 'Content for Soft Launch'

**Comment by angievanhegan** [comment]
@lolmos I've moved this back into backlog for now. Lou's made great progress, but it's one we don't need to focus on for now. When we've got through the global items, then all the events listing page (E), we'll be able to pick this up again.

**Comment by angievanhegan** [comment]
@lolmos Please send me the links so I can review (and move to review column and assign to me) ta.

**Comment by lolmos** [comment]
@angievanhegan here you go:
https://www.dropbox.com/s/6us9rso6fce61ll/Content%20for%20soft%20launch%20only%20Spanish%20and%20English.docx?dl=0

**Comment by angievanhegan** [comment]
@lolmos I think it makes more sense to review this when it's in situ. I'll spot the gaps more easily then. I'll move it to done for now.
