### ISSUE TITLE
Make primary nav and tab options match IA for soft launch version

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#2]
__For Lou to review on PRODUCTION site__

Primary Nav
- [x]  Home
- [x]  Events
- [x] Food and Drink
- [x] Language toggle

Tabs - Home:
- [x] Today
- [x] Food and drink

Tabs - Events section
- [x] Today
- [x] Tomorrow
- [ ] Future

Tabs - Food and drink section
- [x] Restaurants
- [x] Bars
- [x] Street Food

* No content needed on page for this task

**Comment by angievanhegan** [comment]
@lolmos You need to assign this to Lou so that she knows it's one for her to review.

**Comment by lolmos** [comment]
mamzelle Lulis here are the links 
for Primary Nav
http://192.168.1.67:5757/style_guide/styleguide__sectionpage.html
look at the bottom nav

Tabs - Home:
http://192.168.1.67:5757/style_guide/page-styleguide__all-blocks.html

Tabs - Events section- waiting for a fix
http://192.168.1.67:5757/

Tabs - Events section
http://192.168.1.67:5757/en/food-drink/#panel21

**Comment by Loubielou** [comment]
All good; just waiting for the one you need to fix. Then I can sign it off :) P.s.  I like being the boss of signing things off!

**Comment by angievanhegan** [comment]
unblocker is #20

**Comment by lolmos** [comment]
ready to get checked https://the.holboxeno.com/en/

**Comment by lolmos** [comment]
Ready for review
https://the.holboxeno.com/en/

**Comment by angievanhegan** [comment]
@lolmos all signed off (now to look at the styling :o))

It's BRILLIANT to see this on production!! :O)
