### ISSUE TITLE
Monday: Social Media tasks (Lou)

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#229]
- [ ] **Check all forums and answer Holbox questions**
  - [ ] Holboxolics
  - [ ] Yo Amo Holbox
  - [ ] Mochileros en Mexico
  - [ ] All things Holbox
- [ ] **Repost some of our posts in Forums**
  - [x] Holboxaholics
  - [x] Yo Amo Holbox
  - [x] All things Holbox
- [ ] **Check Trip Advisor**
  - [x] Reply in English
  - [x] Reply in Spanish
- [ ] **Generate interest in All things Holbox**
  - [x] Ask question

**Comment by lolmos** [comment]
hey @Loubielou
