### ISSUE TITLE
Finalise hero image for (all) basic events page

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#24]
Used on all basic events
- use svg icon
- All images must have subject centered.
- nothing important should be in the corners.

#### check that scales for header:
- [ ] mobile
- [ ] tablet
- [ ] desktop

#### Lou to approve
- [ ] Lou approves image

**Comment by angievanhegan** [comment]
@lolmos Please send me the links so I can review (and move to review column and assign to me) ta.

**Comment by lolmos** [comment]
@angievanhegan 
https://el.holboxeno.com/en/events/2016/09/01/friday-cinema-mad-max-5

**Comment by angievanhegan** [comment]
@lolmos I see a 'background' type image with diagonal lines.  It doesn't convey any meaning. Is that right?

**Comment by lolmos** [comment]
yes

**Comment by angievanhegan** [comment]
@lolmos aesthetically, I prefer for the whole background to be plain. I don't know what the lines add. They're not beautiful and they don't add meaning. That's just my opinion.
