### ISSUE TITLE
Spirit Hotel: add new content

### ISSUE THREAD

**Issue by Loubielou** [lolmos/statictestting#262]
- [x] Fill out the content form
  - [x] Get images
  - [x] Add them to sales spreadsheet
  - [x] Create business unit on Contentful
  - [x] Write content in English and Spanish
  - [ ] Check Spanish translation
  - [ ] Publish it
  - [ ] Get content approved by the client and make changes
 - [x] Add to appropriate list on Social Media Posts Clients list
 - [x] Add the appropriate number of photos (see above) to Social Media Organized Photos folder
 - [x] Add to the 8 weeks of posts on Social Media Posts excel sheets (1 a week>P, 2 a week>PP)
 - [x] Change details on Clients List Full excel sheet
 - [x] Change details on Accounts

**Comment by Loubielou** [comment]
@lolmos Please check the Spanish here (don't forget to look at the recommendations and extract sections too. Once done, publish it and send it to the client for checking. Thank youuuuuuuuuuuu!

**Comment by lolmos** [comment]
@Loubielou published and sent
