### ISSUE TITLE
Thurs: Viva Zapata: upgrade to Premium

### ISSUE THREAD

**Issue by Loubielou** [lolmos/statictestting#267]
Luis, please can you check the Spanish on this issue in Contentful and then publish it. Once you've done this, please put the issue back in my 'to do this week' column, so I can finish off the tick list. Thanks!! 

### Upgrades
- [x] Get more images (up to 8 Premium, 12 Premium Plus)
- [x] Get any extra info regarding establishment if necessary.
- [x] Rewrite content in Spanish and English
- [x] Check Spanish
- [x] Publish
- [x] Send to client to approve
- [x] Take off Basic Plus Social Media Post spread sheets (if applicable)
- [x] Take off pre-scheduled posts on Hootsuite (if applicable - basic plus only)
- [x] Add to appropriate list on Social Media Posts Clients list
- [x] Add the appropriate number of photos (see above) to Social Media Organized Photos folder
- [x] Change details on Clients List Full excel sheet
- [x] Change details on Accounts
- [x] Notify Client of any money owing/en lieu

**Comment by lolmos** [comment]
Ok bossy boots

**Comment by lolmos** [comment]
Ready @Loubielou, just added a sentence about Chendo:

`This Holboxeño-run restaurant only serves the freshest of ingredients, __owner and Holbox native Chendo goes out fishing every morning to make sure you'll have the best choice of fish.  `

`Este restaurant holboxeño solamente sirve los más frescos de ingredientes. Chendo, el dueño y un nativo de la isla sale todas las mañanas a pescar para asegurar que puedas escoger el mejor pescado. 
`

**Comment by Loubielou** [comment]
Nice

**Comment by Loubielou** [comment]
@lolmos we need to send this to Noa for her to check she's happy with it. As you've been dealing with her, could you do it? Thanks!

**Comment by lolmos** [comment]
Noa said

> [11:20, 8/7/2017] Noa: voy a llorar                        
> [11:20, 8/7/2017] Noa: esta hermoso

**Comment by lolmos** [comment]
there was a change in the website url.
