### ISSUE TITLE
Noa: upgrade to Premium

### ISSUE THREAD

**Issue by Loubielou** [lolmos/statictestting#268]
- [x] Get more images (up to 8 Premium, 12 Premium Plus)
- [x] Get any extra info regarding establishment if necessary.
- [x] Rewrite content in Spanish and English
- [x] Check Spanish
- [x] Publish
- [x] Send to client to approve
- [x] Take off Basic Plus Social Media Post spread sheets (if applicable)
- [x] Take off pre-scheduled posts on Hootsuite (if applicable - basic plus only)
- [x] Add to appropriate list on Social Media Posts Clients list
- [x] Add the appropriate number of photos (see above) to Social Media Organized Photos folder
- [x] Add to the 8 weeks of posts on Social Media Posts excel sheets (1 a week>P, 2 a week>PP)
- [x] Change details on Clients List Full excel sheet
- [x] Change details on Accounts
- [x] Notify Client of any money owing/en lieu

**Comment by Loubielou** [comment]
@lolmos All done here, just need you to check the Spanish then send this to Noa to check she's happy with it. Don't forget to check the Spanish in the recommendations section too. Thanks!

**Comment by lolmos** [comment]
Noa loved it

                        

> [17:19, 8/11/2017] Noa: I love it!                        
> [17:19, 8/11/2017] Noa: " cositas.  Esta foto de tiburon ballena no es mi favorito, podrias poner los primeros 3 fotos al final?                        
> [17:19, 8/11/2017] Elmo: ok!                        
> [17:19, 8/11/2017] Elmo: will tell Lou you liked it                        
> [17:25, 8/11/2017] Noa: Y no se si pueden agregar que soy graduada en Gemology, or Graduate Gemologist                        
> [17:25, 8/11/2017] Noa: Loved it-  she's talented                        
> [17:25, 8/11/2017] Elmo: claro                        
> [17:25, 8/11/2017] Elmo: she is indeed                        
> [17:25, 8/11/2017] Noa: Gracias Luis!                        
> [17:25, 8/11/2017] Elmo: a ti                        
> [17:37, 8/11/2017] Elmo: Noa, owner and designer, was trained and certified as a Graduate Gemologist the US, working for years under some of the top goldsmiths in the country.?                        
> [17:38, 8/11/2017] Noa: Yes!
