### ISSUE TITLE
La Isla> new content

### ISSUE THREAD

**Issue by Loubielou** [lolmos/statictestting#275]
- [x] Fill out the content form
  - [x] Get images
  - [x] Add them to sales spreadsheet
  - [x] Create business unit on Contentful
  - [x] Write content in English and Spanish
  - [x] Check Spanish translation
  - [x] Publish it
  - [ ] Get content approved by the client and make changes
 - [x] Add to appropriate list on Social Media Posts Clients list
 - [x] Add the appropriate number of photos (see above) to Social Media Organized Photos folder
 - [x] Add to the 8 weeks of posts on Social Media Posts excel sheets (1 a week>P, 2 a week>PP)
 - [x] Change details on Clients List Full excel sheet
 - [x] Change details on Accounts

### Basic Plus Listings
- [x] Add three posts to the Basic Plus SM Post spreadsheet
- [x] Manually add these to Hootsuite for the months remaining

**Comment by Loubielou** [comment]
@lolmos Please could you check the Spanish and then publish it. Need to check they've paid for the year so I can add it to the accounts too. When you send the link to them to check if everything is ok, please don't forget to mention the promotions page...I need to get that up and running more!

**Comment by lolmos** [comment]
@Loubielou published and sent to client now waiting approval
