### ISSUE TITLE
Create a viable list of event types

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#28]
This is just a basic list (not everything needed for soft launch)

- [x] Viable list done in English
- [x] Viable list done in Spanish

**Comment by lolmos** [comment]
please check here.
https://contentful.github.io/discovery-app-react/entries/by-content-type/eventType?access_token=70f84814804d4e47f47f945e2c2257cf2e251514bf9081c455b0027098512c6e&preview_access_token=&space_id=5pyzqupsur8u

click on the list on the left hand side and you can see both english and spanish names

**Comment by angievanhegan** [comment]
- Deportes is missing an s (but you have it in twice)
- Sunrise should be capitalised (all the other are) and is missing  in Spanish
- Sunset in Spanish needs correcting

**Comment by lolmos** [comment]
fixed
