### ISSUE TITLE
Rentadora El Cachorro> new content

### ISSUE THREAD

**Issue by Loubielou** [lolmos/statictestting#280]
- [x] Fill out the content form
  - [x] Get images
  - [x] Add them to sales spreadsheet
  - [x] Create business unit on Contentful
  - [x] Write content in English and Spanish
  - [x] Check Spanish translation
  - [x] Publish it
  - [ ] Get content approved by the client and make changes
 - [x] Add to appropriate list on Social Media Posts Clients list
 - [x] Add the appropriate number of photos (see above) to Social Media Organized Photos folder
 - [x] Add to the 8 weeks of posts on Social Media Posts excel sheets (1 a week>P, 2 a week>PP)
 - [x] Change details on Clients List Full excel sheet
 - [x] Change details on Accounts

**Comment by Loubielou** [comment]
@lolmos This is as far as I can get until you get me the other info. I've sent questions you need to ask on Whatsapp. Please take some photos too and then give the issue back to me!

**Comment by lolmos** [comment]
- [x] Opening times                        
- [x] price list                        
- [x] photos                        
- [x] telephone number                        
- [x] email                        
- [ ] can you wahstapp? reserve in advance?                        
- [x] Speak English?                        
- [x] Take cards? Which?⁠⁠⁠⁠

**Comment by lolmos** [comment]
~Por 1 hora: $200 
*Renta mínima de 2 horas 

~Renta todo el día (8:30am a 8:00pm): $1,000 

~24 Horas: $1,500

Tel. 984 8752049
Correo: deptoadmon.cachorro@outlook.com

**Comment by lolmos** [comment]
published but still need some proper pictures

**Comment by lolmos** [comment]
- [x] upload pics
