### ISSUE TITLE
Holbox Transfers> new content

### ISSUE THREAD

**Issue by Loubielou** [lolmos/statictestting#286]
If there's a new customer, create a new issue with these fields (13 points)

- [x] Fill out the content form
 - [x] Get images
 - [x] Add them to sales spreadsheet
 - [x] Create business unit on Contentful
 - [x] Write content in English and Spanish
 - [x] Check Spanish translation
 - [x] Publish it
 - [x] Get content approved by the client and make changes
 - [x] Add to mailing list
 - [x] Add to events update list
 - [x] Add photos (3 BP, 9 P, 18 PP) to SM Organised file in Google Drive
 - [x] Add client to Accounts

Basic Plus Listings

 - [ ] Add three posts to the Basic Plus SM Post spreadsheet
 - [ ] Manually add these to Hootsuite for the months remaining

**Comment by lolmos** [comment]
@Loubielou  here's the info

transfer holbox
transfers
tours 
tulum 
chichen
rio lagaryos
ekbalam
cancun shopping


desde 2001 con vans 2004 primera empresa en vans
30 años desde playa del carmen
primeros en holbox
11 camionetas. trabajan con los hoteles mas grandes 
vans de mercedes 2 transit 3 transportes 2 suburban siena toyota un dodge 2 transporter
de 5 hasta 18 de capacidad.
hasta grupos de 45personas

desde holbox o chiquila.

http://www.transferholbox.com/en/


enriqueram69@hotmail.com
+52 984 875 2104
http://www.facebook.com/transferholbox

**Comment by Loubielou** [comment]
@lolmos Hello! Please could you check the Spanish on this, publish, and then send it to the client to check. Just a little nudge that Noa's still needs checking and publishing too.

**Comment by lolmos** [comment]
Ready @Loubielou
