### ISSUE TITLE
Finalise 3 header images for premium events

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#29]
- use svg icon
- All images must have subject centered.
- nothing important should be in the corners.

### check that image scales for header
- [x] mobile
- [x] tablet
- [x] desktop

**Comment by angievanhegan** [comment]
@lolmos Please send me the links so I can review (and move to review column and assign to me) ta.

**Comment by lolmos** [comment]
Here you go @angievanhegan 
Salsa 
https://el.holboxeno.com/en/events/2016/08/26/salsa-lessons-with-cesar

Yoga
https://el.holboxeno.com/en/events/2016/08/29/yoga-class-at-agua-spa

wellness
https://el.holboxeno.com/en/events/2016/09/03/undefined

**Comment by angievanhegan** [comment]
@lolmos they don't go to full width when horizontal on the iphone and ipad. Is that right?Looks fine to me though.
