### ISSUE TITLE
Naay Salad bar> new content

### ISSUE THREAD

**Issue by Loubielou** [lolmos/statictestting#294]
- [x] Fill out the content form
  - [x] Get images
  - [x] Create business unit on Contentful
  - [x] Write content in English and Spanish
  - [x] Check Spanish translation
  - [x] Publish it
  - [ ] Get content approved by the client and make changes
 - [x] Add to appropriate list on Social Media Posts Clients list
 - [x] Add the appropriate number of photos (see above) to Social Media Organized Photos folder
 - [x] Add to the 8 weeks of posts on Social Media Posts excel sheets (1 a week>P, 2 a week>PP)
 - [x] Change details on Clients List Full excel sheet
 - [x] Change details on Accounts

**Comment by Loubielou** [comment]
@lolmos Done! Please check and then send to client. Don't forget to mention the promos!

**Comment by lolmos** [comment]
done

**Comment by lolmos** [comment]
Text changes have already been made
### update images on contentful

- [x] put images in contentfull images
- [x] rename to spanish
- [x] rename to english
- [x] upload to contentful
- [x] replace images that are stock images
