### ISSUE TITLE
Finalise footer

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#3]
Done criteria

__Test for Luis__
- [x] Looks ok on iphone 5
- [ ] Looks ok ipad mini
- [x] Looks good enough at desktop
- [ ] Works ok on Firefox
- [x] Works ok on Chrome
- [ ] Works ok on IE 10

__Sign off for Lou__
- [x] Final text for copyright
- [x]  Whatsapp number
- [x] Link to Google form
- [x] Design approed
- [x] Text all approved (ES and EN)

**Comment by lolmos** [comment]
ready for review 
https://the.holboxeno.com/en/

**Comment by angievanhegan** [comment]
@lolmos Personally, I found the vertical stacking took me a moment to work out (although visually, it is neat). Something like this might be easier?

Get listed: What'sApp 984-111-1111 or online form
All content copyright El Holboxeño 2016

Also, WhatsApp is all one word with a capital A. And 'copyright' should have a lower case c.

**Comment by lolmos** [comment]
added a bit more room in between the columns and changed the text

**Comment by angievanhegan** [comment]
@lolmos Is this ready for me to review? Ta

**Comment by angievanhegan** [comment]
@lolmos I can't see the footer changes on here: https://the.holboxeno.com/en/. Also, I can only see the footer on the food and drink page. I can't see it on events or home.

**Comment by angievanhegan** [comment]
@lolmos footer doesn't appear on 'tomorrow' tab - is this because there's no content?

**Comment by lolmos** [comment]
tested in firefox

**Comment by lolmos** [comment]
tested in ipad air 2

**Comment by lolmos** [comment]
tested in firefox
