### ISSUE TITLE
Upload text and images for 3 basic event and 3 premium event pages

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#30]
Use content from #26, #27, #24

__For Lou to review on PRODUCTION site__
3 basic events
- [x]  Baseball
- [x] water yoga
- [x] Film

3 Premium events
- [x] Tribu
- [x] Yoga La Casa Tortugas
- [x] I love me wellness

__Overall__
- [x] All information visible (in Spanish AND English)
- [x] Images available for Premium events
- [x] Placeholder image for Basic events
- [x] Language toggle works
- [x] Nothing that was working before is broken now!

**Comment by angievanhegan** [comment]
@lolmos Please send me the links so I can review (and move to review column and assign to me) ta.

**Comment by lolmos** [comment]
Cinema
https://el.holboxeno.com/en/events/2016/09/01/friday-cinema-mad-max-51

https://el.holboxeno.com/en/events/2016/08/28/self-discovery-in-motion-water-yoga-dynamics-in-holbox.html

**Comment by angievanhegan** [comment]
@lolmos cinema link doesn't work

ES - Beisbal *en* Holbox?
No map for baseball
