### ISSUE TITLE
Create new repeatable-event Bootcamp light

### ISSUE THREAD

**Issue by lolmos** [lolmos/statictestting#301]
- [ ] playa de ñaña lunes miércoles y viernes a las 8 a 8:45
 this is from Emiliano

> Holbox Bootcamp Lite fue creado para brindar una clase a todas aquellas personas que carecen de condicion física, están excedidos de peso, padezcan alguna lesión o simplemente el Bootcamp convencional le parezca muy fuerte.
> 
> Las clases serán de baja intensidad y bajo impacto enfocadas en el funcionamiento del cuerpo y con el objetivo de ganar condicion, Fuerza, agilidad, una mayor movilidad y perder peso.

**Comment by lolmos** [comment]
Playa de Ñaña is next to Mawimbi

**Comment by Loubielou** [comment]
@lolmos Done. Please could you check the Spanish and don't forget to look at the except below. Thanks! P.s. I've already published it.

**Comment by lolmos** [comment]
@loubielou looks good
