### ISSUE TITLE
Crear Quick list de respuestas rápidas

### ISSUE THREAD

**Issue by AguirreDiana** [lolmos/statictestting#313]

**Comment by Loubielou** [comment]
@AguirreDiana Ya he empezado esto. Lo puedes encontrar en una carpeta en Google Drive. Los comentarios para usar en Twitter e Instagram los he escrito en inglés pero quizas es mejor si tu los escribas en español :) Podemos ir añadiendo más según las fotos en las que hacemos comentarios, o las preguntas en los forums.

**Comment by AguirreDiana** [comment]
Listo ya he empezado con los comentarios en español y alguno que otro en frances.
