### ISSUE TITLE
Frexco - design vinils

### ISSUE THREAD

**Issue by lolmos** [lolmos/statictestting#322]
### prepare files
- [x] out right: 61cmx201cm (
- [x] centre: 74cmx180cm
- [x] out left: 74x201cm
- [x] fridge panels: top 21.5cm bottom 30.8cm height 111cm inside  112 outsite
- [x] top bar 125 wide usable 9.5 cm front total height 17cm wraparound
- [x] shelves front 123.5 x 4cm. x4

- [x]  make master texture file
side windows

- [x] right 190x93
- [x] left 92.5x190

- [ ] edit images
- [ ] add images

**Comment by lolmos** [comment]
@AguirreDiana Recaping what we said yesterday:
### windows front
- [x] make green background fit inside the page
- [x] remove some veggies and make more space.
- [x] add text on the food bubbles (baguette, vegan options, smoothies)
   - [x] add orange block with white text
       - [x]  make an orange version of green background
          - [x] make new file with orange in name
          - [ ] change background colour to orange 
### windows side
- [x] make green background fit inside the page
- [x] remove some veggies and make more space.
- [x] add text on the food bubbles (baguette, vegan options, smoothies)
- [x] make sure that it works as one piece

### fridge side panels
- [x] make green texture smaller
- [x] add text and veggies

### fridge front strips
- [x] top panel - logo in center
- [x] add diferent version for bottom panel
   - [x] add logo without the text at bottom
   - [x] next to logo add the text in big size (fresh , fast , healthy)

**Comment by AguirreDiana** [comment]
- [ ] Crecar Etiquetas de precios
