### ISSUE TITLE
Publish metadata for events, BUs and pages

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#33]
The following fields can be viewed and/or  used by the relevant site:
- [x] title
- [x]  hreflang es_MX
- [x]  hreflang en_US
- [x] Meta keywords
- [x] Meta description
- [x] OG title
- [x] OG type
- [x] OG description
- [x ] OG url
- [x]  og locale
- [x]  og locale alternate
- [x]  twitter summary or summary_large_image
- [x] Twitter site
- [x] Twitter title
- [x] Twitter description
- [x]  twitter image
- [x]  twitter image_alt

**Comment by lolmos** [comment]
done!!

**Comment by lolmos** [comment]
@angievanhegan check the head of a page, an event and a business unit please

**Comment by angievanhegan** [comment]
@lolmos I can´t find the ones I haven´t ticked. 

Also, I´m adding another issue to test that these are all working as they should be. i.e. twitter is displaying the data you want it to.

**Comment by lolmos** [comment]
ready for you to check again

**Comment by angievanhegan** [comment]
@lolmos I can't find anything that just refers to hreflang (only when it specifies the two languages). I'm assuming that's right, but the list above suggests I'm looking for three separate things.

Also, is this right for the twitter summary?

<meta name="twiter:card" content="summary_large_image">

**Comment by lolmos** [comment]
@angievanhegan, oops you're right it should only be the two references removed the extra item
