### ISSUE TITLE
banner "para ti"

### ISSUE THREAD

**Issue by lolmos** [lolmos/statictestting#347]
they want to change it to the originals with the map
sent the original to the folder on canica 2

**Comment by AguirreDiana** [comment]
ya lo puse en la carpeta de topress, checalo y me dices si así te parece bien @lolmos

**Comment by lolmos** [comment]
@AguirreDiana 
[12:29 PM, 10/11/2017] Gerardo Avila: hola Luis...   disculpa...   recuerda solo ponerle   

- [ ] -Botellas de plástico   
- [ ] - Latas de aluminio ..    
- [ ] también le falta el mensaje :"Cuidemos Holbox"

checar en correo original por el mensage
