### ISSUE TITLE
Lista de entrega

### ISSUE THREAD

**Issue by AguirreDiana** [lolmos/statictestting#355]
### Mapas
- [x] hacer lista de clientes con fechas de entregas
- [x] establecer rondas diarias para entregar mapas a hoteles

**Comment by lolmos** [comment]
More maps to
- [x] TUI at Villas Jardín
- [x] Villas Margaritas
- [x] Temazcal Itxchel

**Comment by lolmos** [comment]
- [x] hotel para ti
