### ISSUE TITLE
Create new BU 

### ISSUE THREAD

**Issue by lolmos** [lolmos/statictestting#356]
erika huerta
make up artis
998152 62 98
erikahuertamakeup@gmail.com
erikahuertamakeup intsa

fb: Erika Huerta Makeup get pictures from there. and Instagram

maquillaje debnovia y social. especialidad de novia de pkaya y maquillaje en clima humedo. resistente al agua y sudor puedes hacer crash thr dress

con 3 años de xperiwncia en labriviera maya. 

  - [x] Fill out the content form
  - [x] Get images
  - [x] Create business unit on Contentful
  - [x] Write content in English and Spanish
  - [ ] Check Spanish translation
  - [ ] Publish it
  - [ ] Get content approved by the client and make changes
 - [x] Add to appropriate list on Social Media Posts Clients list
 - [x] Add the appropriate number of photos (see above) to Social Media Organized Photos folder
 - [ ] Add to the 8 weeks of posts on Social Media Posts excel sheets (1 a week>P, 2 a week>PP)
 - [x] Change details on Clients List Full excel sheet
 - [x] Change details on Accounts

### Basic Plus Listings
- [x] Add three posts to the Basic Plus SM Post spreadsheet
- [x] Manually add these to Hootsuite for the months remaining

**Comment by Loubielou** [comment]
Please check the Spanish @lolmos and also the address part. Then send it to her for checking!
