### ISSUE TITLE
Complete build for header

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#4]
Assumes the following are done: Section copy #7, hero images #6, colours #9,  typography #10, content in system #12

__Test for Luis on Production__
- [ ] Looks ok on iphone 5
- [ ] Looks ok ipad mini
- [ ] Works ok on Firefox (and resizes ok)
- [ ] Works ok on Chrome (and resizes ok)
- [ ] Works ok on IE 10

__Tests for each device__
- [ ] Mobile and desktop users are getting the optimal image size
- [x] Logo appears correctly
- [x] Right header appearing on right page
- [x] Gate text function can show/hide as per design (for all widths and devices)
- [x] Images  and alt text * 3 behave correctly with language toggle
- [x] Text  * 3 behave correctly with language toggle

__Lou to do final sign off on production__
- [ ] Design ok
- [ ] Functionality all ok

**Comment by lolmos** [comment]
found an issue on the ipad. the resolution is too big need to add one more viewport size

**Comment by lolmos** [comment]
Explorer 10 also being  funny

**Comment by lolmos** [comment]
ipad issue resolved

**Comment by lolmos** [comment]
@angievanhegan hello

**Comment by angievanhegan** [comment]
@lolmos Is this ready for me to test? I'm assuming it is because it's in the review column, but if you assign it to me then I'll defo know. :o)

**Comment by angievanhegan** [comment]
Chrome:

1.  the horizontal line goes under the 'read more' box on the left hand side
2. the horizontal line does not join with the right hand edge of the 'read more' box (I like the look of it without the box but it'd be interested to see if users took the fact that it's a verb to mean that it was a link)
3.  Home page only: the 'hide' button at the bottom sits against the navigation tabs on the english version and overlaps it slightly on the Spanish version. It also does this on the other pages at narrower widths
4. the top hide button overlaps the logo when I reduce the screen width
5. when I switch between languages, the images reload (could it reuse the image it already downloaded to make it faster?)
6.  I'm not enjoying the way the heading text dynamically resizes. It feels messy to me. This is made worse by the fact that some of the page furniture is also shifting vertical height when the page reloads (header text and horizontal line)

Firefox

(3) above (but not at all narrower widths)

**Comment by angievanhegan** [comment]
### Chrome:

3.  All pages. At certain widths the  'hide' button at the bottom still overlaps the tabs below it. Sometimes completely.  
4. the top hide button overlaps the logo when I reduce the screen width
6.  When the heading text increases in size, it's still jumpy. 

### Firefox

(3) above (but not at all narrower widths)

### iPhone SE Chrome and Safari - all good

### Ipad

(3) above on horizontal view only

### Windows

Please can you test this? 

Overall - its quite fast, but not super fast for me. I know it's Holbox in the afternoon, but that's when a lot of people might be using it. Could it not show the header image if it's below a certain bandwidth? It looks good without them, and they'd have the content.

Also, I think we should prioritise #45 - it's much more of an issue on mobiles.
