### ISSUE TITLE
Check Cron jobs working

### ISSUE THREAD

**Issue by lolmos** [lolmos/statictestting#40]
Do we have any logs of when the cron job runs? 
Please check that they are set and working correctly

**Comment by angievanhegan** [comment]
@lolmos is this a bug?

**Comment by Rodolfocartas** [comment]
I've set a netlify incoming webhook and a cron job at crondash.com. The jobs will run every day at midnight Mexico City time.

**Comment by lolmos** [comment]
ok can you change that to be cancun time because we are not mx time anymore

**Comment by lolmos** [comment]
@Rodolfocartas  can you change that to Cancun time please? we aren't mx time anymore

**Comment by Rodolfocartas** [comment]
The closest I can choose is Merida Time.

**Comment by Rodolfocartas** [comment]
I found out that Eastern Time Zone is compatible with Cancun Time Zone. Set.
