### ISSUE TITLE
Redirects

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#42]
- [ ] www. holboxeno.com redirects to a home page
- [ ] default homepage is spanish

**Comment by lolmos** [comment]
have the subdomains working fine now.
We need to figure out weather www. redirects geographically or we just choose a default

**Comment by angievanhegan** [comment]
@lolmos  This isn't working for me on chrome (I haven't tried anywhere else). I've tried https and http.  http redirects to https, but I still get a 'page not found' error.

**Comment by lolmos** [comment]
done!

**Comment by lolmos** [comment]
@angievanhegan if you go to www.holboxeno.com it should take you to el.holboxeno.com whilst in Mexico if you are in USA or Europe (except Portugal,Spain and Italy) it takes you to the.holboxeno.com
