### ISSUE TITLE
Update BUs on map

### ISSUE THREAD

**Issue by lolmos** [lolmos/statictestting#420]
### remove
- [x] El Crustaceo Kascarudo -- marker
- [x] El Crustaceo Kascarudo -- list

### downgrade

- [x] Parador -- marker
- [x] Parador -- list
- [x] Limoncito -- list
- [x] roots -- list
- [x] VIP -- marker
- [x] VIP -- list

### upgrade

- [x] Los Arcos  -- list--falta logo
- [x] mosquitours  -- list--falta logo
- [x] abominable maria  -- list and change to restaurant
- [x] Le bazzar -- to premium plus -- falta logo
- [x] Le bazzar -- to premium plus -- falta logo
- [x] naay  -- marker
- [x] naay -- list
- [x] Alma  -- marker premium +
- [x] Alma -- list Premium +

### new

- [x] Holbox Holmes -- list premium
- [x] Holbox Holmes  -- marquer
- [x] Negromaco (BP)-- list basic
- [x] Negromaco (BP)  -- marquer
- [x] Spa woman (BP)-- list basic
- [x] Spa woman (BP)  -- marquer
- [x] tacoqueto-- list premium
- [x] tacoqueto  -- marquer
- [x] villas los mangles-- list basic
- [x] villas los mangles
- [x] carita-- list basic
- [x] carita  -- marquer
- [x] Porqué No -- list basic 
- [x] Porqué No   -- marquer
- [x] mandarina -- list premium +
- [x] mandarina  -- marquer
- [x] luuma -- list premium +
- [x] luuma  -- marquer
- [x] big fish -- basic plus +
- [x] big fish  -- marquer
- [x] palapa del Sol -- list premium plus +--falta logo
- [x] palapa del sol  -- marquer 
- [x] Cariocas Bar - premium --falta logo

#### print and check

**Comment by AguirreDiana** [comment]
Logotipos faltantes:

- [x] -milpa
- [x] -la parrilla de juan
- [x] -le bazaar
- [x] -los arcos
- [x] -mosquitours
- [ ] -cariocas bar
- [x] -palapas del sol

**Comment by lolmos** [comment]
el de mosquitours se lo pedí a Limbert. @AguirreDiana  porfa persiguelo para que te lo pase
Palapas del sol. Ahora te paso una imagen para que la digitalices

**Comment by lolmos** [comment]
- [x] Parilla de Juan - upgrade premium plus
- [x] nay- get slogan and update contact info
- [x] los arcos - logo
- [x] Palapas del sol - update slogan and contact info

**Comment by lolmos** [comment]
- [x] Hostal Casa Holbox - basic plus
- [x] utstal básico plus

**Comment by lolmos** [comment]
- [x] - HM Villas Paraiso del mar - Premium
- [x] - Restaurant Paraíso - Premium Plus
