### ISSUE TITLE
events frame in hidden tabs width 0

### ISSUE THREAD

**Issue by lolmos** [lolmos/statictestting#44]
the events images in hidden tabs down't find the image size and don't show the image

**Comment by lolmos** [comment]
not sure what happened here but it's working now

**Comment by lolmos** [comment]
@angievanhegan  can you check on your machine and iphone?
just go from one tab to the other and make sure the images are loaded  (before the ones in the hidden tab would nt show the image when made visible.

**Comment by angievanhegan** [comment]
@lolmos you'll have to explain this to me :o)
