### ISSUE TITLE
Primary nav: horizontal area above and below text is not a link

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#45]
__Test for Luis__
- [x] iphone 5
- [x] Ipad mini
- [x] desktop
- [x] Firefox
- [x] Chrome
- [x] IE 10

**Comment by angievanhegan** [comment]
@lolmos This is much more a problem on my phone. the actual link are is so small. I keep pressing it and it doesn't do anything (because I've not actually pressed the link)

**Comment by lolmos** [comment]
Ok should be ready for checking now

**Comment by angievanhegan** [comment]
@lolmos I´m missing an adaptor to setup IE10. I've tested and signed off everything else. Can you just check it in IE10 then move to done? Thanks
