### ISSUE TITLE
Finalise hero images for header

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#6]
Done criteria
- [x] Finalise minimum size
- [x] Home  image
- [x] Food and Drink header image
- [x] Events image
- [ ]  Lou approved images

**Comment by lolmos** [comment]
they are live now
https://the.holboxeno.com/en/
password: mapache

**Comment by angievanhegan** [comment]
@Loubielou These all work fine. It's jut down to you to decide if these images are 'right' (enough) for a soft launch.

**Comment by angievanhegan** [comment]
@Loubielou Please can you have a look at the images for the home page, food and drinks and events and see if you think the image is ok for this purpose? Is it pretty, colourful, convey the right impression etc etc Please add your feedback here. Writing it down should help make it specific :o) Thanks.

**Comment by angievanhegan** [comment]
@lolmos I noticed that the crop of these works much better on the ipad and iphone. I'm assuming that's intentional.
