### ISSUE TITLE
Finalise content and images for  Milpa (Premium +)

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#60]
then do #55

- [x] BU name
- [x] Business type
- [x] Business sub type
- [x] Food types
- [x] Cost low/high
- [x] opening time (english)
- [x] opening time Spanish
- [x] geo location
- [x] meta title English
- [x] Meta title Spanish
- [x] OG desc Eng
- [x] OG desc Spanish
- [x] Keywords English
- [x] Keywords Spanish
- [x] Twitter description English
- [x] Twitter description Spanish
- [x] Premium
- [x] Premium plus
- [x] Twitter account
- [x] Facebook account
- [x] Gallery images English
- [x] Gallery images Spanish
- [ ] Website
- [x] Amenities
- [x] Body copy English
- [x] Body copy Spanish
- [x] Recommendations English
- [x] Recommendations Spanish
- [x] Listing feature title English
- [x] Listing feature title Spanish
- [x] Listing feature image
- [x] Listing feature copy English
- [x] Listing feature copy Spanish

**Comment by lolmos** [comment]
https://www.dropbox.com/s/6us9rso6fce61ll/Content%20for%20soft%20launch%20only%20Spanish%20and%20English.docx?dl=0

**Comment by angievanhegan** [comment]
@lolmos You need to finish this - I can't complete any more
