### ISSUE TITLE
Design default image for basic events, basic business unit, food place

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#61]
- [x] default image for basic events
- [x] default image for basic business unit
- [x] default  image for food place

**Comment by lolmos** [comment]
As we agreed to only use one I have done that. Please check

https://el.holboxeno.com/comer-y-beber-en-holbox/
https://el.holboxeno.com/comer-y-beber-en-holbox/restaurant-45-basic-no-pic
https://el.holboxeno.com/eventos/2016/09/02/cine-de-viernes-mad-max-5

**Comment by angievanhegan** [comment]
@lolmos What is the second link showing please?  First and third ones look great to me. 

IMHO it's worth having a different image for each of the purposes. It might be confusing to have the same image having some meaning for three quite different things.  I appreciate that it's more work though. It's up for you!
