### ISSUE TITLE
Finalise content for Cariocas (Premium)

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#68]
# BUSINESS UNIT CHECKLIST

### Basic
- [x] BU name
- [x] Business type
- [x] Business sub type
- [x] What to expect
- [ ] Cost low/high
- [x] opening time (english)
- [x] opening time Spanish
- [x] geo location
- [x] meta title English
- [x] Meta title Spanish
- [x] Body copy English
- [x] Body copy Spanish
- [ ] Telephone
- [x] Address

### Premium
- [x] OG desc Eng
- [x] OG desc Spanish
- [x] Keywords English
- [x] Keywords Spanish
- [x] Twitter description English
- [x] Twitter description Spanish
- [ ] Twitter account
- [x] Facebook account
- [x] Gallery images English
- [x] Gallery images Spanish
- [ ] Website
- [x] Amenities
- [x] Recommendations English
- [x] Recommendations Spanish

### Premium +
- [ ] Listing feature copy English 
- [ ] Listing feature copy Spanish
- [ ] Listing feature title English
- [ ] Listing feature title Spanish
- [ ] Listing feature image

**Comment by lolmos** [comment]
done
