### ISSUE TITLE
Finalise section page copy

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#7]
Done criteria - Lou to approve
- [x]  Nightlife copy - English
- [x]  Nightlife copy - Spanish
- [x]  Home copy - English
- [x]  Home copy - Spanish
- [x]  Events  copy - English
- [x]  Events copy - Spanish
- [x]  Food and drink copy - English
- [x]  Food and drink  copy - Spanish

Done criteria - Luis to double check
- [x]  Nightlife Spanish
- [x]  Home Spanish
- [x]  Events Spanish
- [x]  Food and drink Spanish

**Comment by angievanhegan** [comment]
Needs to be assigned to Lou

**Comment by Loubielou** [comment]
Bee...I need the link to the files, pleaseeeeee

**Comment by lolmos** [comment]
Look at this file please

https://www.dropbox.com/s/86jxia15mlvl2o2/content%20for%20translation.docx?dl=0

**Comment by Loubielou** [comment]
Luis, I need to you to have a read over the Spanish again to make sure it's all ok. I've corrected the errors, but I need a native's eyes for the final check. Also, the home page text is great, but it includes information beyond restaurants, bars and events. What do you want me to do?
