### ISSUE TITLE
Finalise Business unit listing for basic BU

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#70]
- [x] BU name
- [x] Food types 
- [x] Cost low/high
- [x] opening time (english)
- [x] opening time Spanish
- [x] geo location
- [x] meta title English
- [x] Meta title Spanish
- [x] OG desc Eng
- [x] OG desc Spanish
- [x] Keywords English
- [x] Keywords Spanish
- [x] Twitter description English
- [x] Twitter description Spanish
- [x] Body copy English
- [x] Body copy Spanish

**Comment by lolmos** [comment]
@angievanhegan  test with this link please:
https://el.holboxeno.com/comer-y-beber-en-holbox/street-food-3-premium

**Comment by angievanhegan** [comment]
- Same comment about the missing yellow headers

**Comment by angievanhegan** [comment]
@lolmos back to you.
