### ISSUE TITLE
Finalise Business Unit listing for Premium BU

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#71]
- [x] BU name
- [x] Food types 
- [x] Cost low/high
- [x] opening time (english)
- [x] opening time Spanish
- [x] geo location
- [x] meta title English
- [x] Meta title Spanish
- [x] OG desc Eng
- [x] OG desc Spanish
- [x] Keywords English
- [x] Keywords Spanish
- [x] Twitter description English
- [x] Twitter description Spanish
- [x] Twitter account
- [x] Facebook account
- [x] Gallery images English
- [x] Gallery images Spanish
- [x] Website
- [x] Amenities
- [x] Body copy English
- [x] Body copy Spanish
- [x] Recommendations English
- [x] Recommendations Spanish
- [x] Listing feature title
- [x] Listing feature image
- [x] Listing feature copy

**Comment by lolmos** [comment]
@angievanhegan test with this link please:
https://el.holboxeno.com/comer-y-beber-en-holbox/street-food-3-premium

**Comment by angievanhegan** [comment]
-  how come no yellow highlight block on these? It's a gorgeous way to highlight the most important info?

**Comment by angievanhegan** [comment]
@lolmos Back to you. Looks really great!

**Comment by lolmos** [comment]
I believe this is done now

**Comment by lolmos** [comment]
updated the top bit with the title
and have place markers for each business type

**Comment by lolmos** [comment]
https://57f2d1c0a7e2d24dc76df2e1--project-mapache.netlify.com/en/food-drink-in-holbox/cariocas-beach-bar
