### ISSUE TITLE
Add some basic analytic

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#79]
- [x] Can see which IP people are coming from
- [x] See most popular entry pages
- [x] See number of visits
- [x] See number of unique visitors
- [x] See dwell time and bounce rate

**Comment by lolmos** [comment]
have added you to the analytics

**Comment by angievanhegan** [comment]
@lolmos I have to confess, I can't actually find any of the things listed above in the acceptance criteria, but it seems to be working overall!
