### ISSUE TITLE
Styling for primary nav and and tabs

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#8]
Done criteria

__Test for Luis on PRODUCTION__
- [x] Looks ok on iphone 5
- [x] Looks ok ipad mini
- [x] Looks good enough at desktop
- [x] Works ok on Firefox
- [x] Works ok on Chrome
- [ ] Works ok on IE 10

__Lou to sign off on PRODUCTION__
- [x] Primary nav styled (at the bottom)
- [x] Tabs styled (top and bottom ones)
- [x] Flag appears in translate button

**Comment by lolmos** [comment]
https://the.holboxeno.com/en/

**Comment by angievanhegan** [comment]
@lolmos Some feedback on the styling. You can ignore these comments if you want to. If you want to ignore these, then I'll do a final review (i.e all the devices testing)

1. Love the yellow highlight on the primary nav to show where you are, but it doesn't work for the 'events' and 'food and drink' sections.

2. When I click on a tab (in Chrome) it gives it a blue outline, which doesn't look that great. Can you get rid of this, or change it to the green? Let me know if you need a screen print.

3. My initial impression of the thin strip of colour on the primary nav and the tabs was that it was confusing. I deduced the meaning (although it took effort to work it out that I think you don't want your users to have to make) but overall I think it didn't help me and it just adds some confusion (the use of colours isn't 100% consistent between the nav and tabs, although I understand why, and this layers another level of inconsistency on top of it). I'd definitely prefer it without these strips. Personally, I think the  simpler/cleaner the better.

4. The hover over the Mexican/English flags puts two white corners on the bottom and two pale green ones on the top. Does this need a different hover style? Does it need a hover style at all? 

5. Toggling between the two flags: From Mexican to English, the tabs and white text slide up the screen about 10 - 20 px. From English to Mexican, the change happens in reverse.

If you reply to each of these by number below, you can let me know if you want me to retest, clarify or ignore. Thanks.

**Comment by angievanhegan** [comment]
From Luis, to do:

1. to do
2. angie to crete a bug issue

**Comment by lolmos** [comment]
2. seems harder than I thought
chrome adds it's own accessability css to all pages and hence the blue glow on elements that are focused.
Tried the few clues online but they are all old. seems chrome just pushes it on.

**Comment by lolmos** [comment]
3 DOne

**Comment by lolmos** [comment]
4 done

**Comment by lolmos** [comment]
5 done

**Comment by lolmos** [comment]
1 works on home and events but blocked on food and drink. need to ask Rodolfo to look into it

**Comment by lolmos** [comment]
The blocker for this has been transferred to issue 38
@angievanhegan what should I do with this now?

**Comment by angievanhegan** [comment]
This is being unblocked by #38

**Comment by lolmos** [comment]
done

**Comment by angievanhegan** [comment]
@lolmos I'm just downloading Firefox again.

**Comment by angievanhegan** [comment]
@lolmos where you said this:

1. seems harder than I thought chrome adds it's own accessability css to all pages and hence the blue glow on elements that are focused. Tried the few clues online but they are all old. seems chrome just pushes it on.

Did you mean 2?
