### ISSUE TITLE
enhance srctset plugin

### ISSUE THREAD

**Issue by lolmos** [lolmos/statictestting#88]
add an option for changes depending if even, slider garl or section page

**Comment by lolmos** [comment]
check
https://the.holboxeno.com/food-drink-in-holbox/street-food-3-premium
and  
https://the.holboxeno.com/food-drink-in-holbox/restaurant-11-basic
and
https://the.holboxeno.com/food-drink-in-holbox/restaurant-45-basic-no-pic

**Comment by angievanhegan** [comment]
@lolmos What needs checking here?

**Comment by angievanhegan** [comment]
@lolmos Nice!
