### ISSUE TITLE
CHECKLISTS

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#91]
# BUSINESS UNIT CHECKLIST
### Basic
- [ ] BU name
- [ ] meta title English
- [ ] Meta title Spanish
- [ ] Short description English 
- [ ] Short description Spanish
- [ ] Business type
- [ ] Business sub type
- [ ] What to expect
- [ ] Cost low/high*
- [ ] opening time (english)*
- [ ] opening time Spanish*
- [ ] Telephone*
- [ ] geo location
- [ ] Address
### Basic plus
- [ ] Gallery image English (only one!)
- [ ] Gallery image Spanish (sólo una!)
### Premium
- [ ] Body copy English
- [ ] Body copy Spanish
- [ ] OG desc Eng
- [ ] OG desc Spanish
- [ ] Keywords English
- [ ] Keywords Spanish
- [ ] Twitter description English
- [ ] Twitter description Spanish
- [ ] Twitter account
- [ ] Facebook account
- [ ] Gallery images English
- [ ] Gallery images Spanish
- [ ] Website
- [ ] Amenities
### Premium +
- [ ] Listing feature copy English 
- [ ] Listing feature copy Spanish
- [ ] Listing feature title English
- [ ] Listing feature title Spanish
- [ ] Listing feature image

**Comment by angievanhegan** [comment]
# EVENT CONTENT CHECKLIST

### Basic
- [ ] Place holder header image
- [ ] Event title English
- [ ] Event title Spanish
- [ ] Event date
- [ ] Start time and end time
- [ ] Price
- [ ] Event types (English and Spanish)
- [ ] Short event description English
- [ ] Short event description Spanish
- [ ] Event amenities (English and Spanish)
- [ ] Contact phone number
- [ ] Link to business unit
- [ ] Address
- [ ] Geo location


### Premium
- [ ] Image
- [ ] Full body copy English
- [ ] Full body copy Spanish
- [ ] OG desc Eng
- [ ] OG desc Spanish
- [ ] Keywords English
- [ ] Keywords Spanish
- [ ] Twitter description English
- [ ] Twitter description Spanish

**Comment by lolmos** [comment]
@angievanhegan heres's the spreadsheet https://www.dropbox.com/s/qazzc3l3ahlnfxy/PREPA%20BASIC%20FOOD%20%26%20DRINK.xlsx?dl=0
