### ISSUE TITLE
Setup test environment

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#94]
- [x] in production environment
- [x] webhook from gitbucket 
- [x] app configuration file
- [x] contentful config file

**Comment by lolmos** [comment]
Done. 
production is still: holboxeno.com

Dev is now : https://develop--project-mapache.netlify.com

**Comment by lolmos** [comment]
will need to add a per feature branch URL when testing per feature .\Netlify ROCKS!!!!
