### ISSUE TITLE
Add a few key landmarks to the map to help new people orientate themselves

### ISSUE THREAD

**Issue by angievanhegan** [lolmos/statictestting#95]
- [x] The square?
- [x] The pier
- [x] The market?
- [ ] ?

**Comment by lolmos** [comment]
https://api.mapbox.com/styles/v1/canicacuadrada/ciixbebgt00m18tm0yp0jq3pb.html?title=true&access_token=pk.eyJ1IjoiY2FuaWNhY3VhZHJhZGEiLCJhIjoiUGZxWkRHRSJ9.f4IDZr9XFGFeEHie7rcCCA#12.96/21.527601292980364/-87.37799877131957/0

**Comment by angievanhegan** [comment]
@lolmos 

Nice. Just a couple of personal opinions:

- the map is gorgeous, but the pier looks a bit like I did it! 
- it's very frustrating that the pink icons (which look great) but don't actually tell me anything very useful. I'd really want to click on them (I'd be very frustrated that you have this information and you're not giving it to me!) or at the minimum, they have a name (which might make the map look cluttered)
- seeing as the market is an area of other businesses, it might be nice to show it as an area. Perhaps the same for the mall which is also quite a landmark (I think) as it has a lot of other shops in it. And it's big.
